driver:
  name: vagrant

provisioner:
  name: chef_solo
  product_name: chef
  # Uncomment when testing idempotency
  # The add & delete key in dummy_key.rb breaks this right now (on purpose)
  # enforce_idempotency: true
  # multiple_converge: 2
  solo_rb:
    treat_deprecation_warnings_as_errors: true

verifier: inspec

platforms:
  - name: amazon-linux
    driver_config:
      box: mvbcoding/awslinux
  - name: centos-6
  - name: centos-7
  - name: debian-8
  - name: debian-9
  - name: fedora-28
  - name: ubuntu-16.04
  - name: ubuntu-18.04

suites:
  - name: default
    run_list:
    - recipe[test::default]
